<a href="https://colab.research.google.com/github/Lokeshrathi/PyTorch/blob/main/PyTorch_Bascis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install torch

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


## Create a tensor:

### Tensor is a data structure to save data for PyTorch!

In [2]:
import torch
import numpy as np

In [3]:
array = [[1,2],[4,5],[7,2]]

tensor1 = torch.tensor(array)
print(tensor1)

tensor([[1, 2],
        [4, 5],
        [7, 2]])


## Slicing

In [4]:
tensorA = torch.tensor([[1,1,1],[2,2,2],[3,3,3]])
print(tensorA[:2,:2])

tensor([[1, 1],
        [2, 2]])


## Concatenate

In [5]:
tensorA = torch.tensor([[1,1,1],[2,2,2],[3,3,3]])
tensorB = torch.tensor([[3,5,7],[9,8,7],[0,9,3]])

concat_v = torch.cat([tensorA,tensorB])
print("Concatenate Vertically \n",concat_v)

concat_h = torch.cat([tensorA,tensorB],dim=1)
print("Concatenate Horizontally \n",concat_h)

Concatenate Vertically 
 tensor([[1, 1, 1],
        [2, 2, 2],
        [3, 3, 3],
        [3, 5, 7],
        [9, 8, 7],
        [0, 9, 3]])
Concatenate Horizontally 
 tensor([[1, 1, 1, 3, 5, 7],
        [2, 2, 2, 9, 8, 7],
        [3, 3, 3, 0, 9, 3]])
